config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/art'
  resources :articles
  resources :posts
  devise_for :users
  resources :movies
  get 'home/index'
  resources :lists
  #root "articles#index"
  root "home#index"
  #root "pages#art"
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
  has_rich_text :body
  has_many_attached :files

  def files_as_thumbnails
    files.map do |file|
      file.variant(resize_to_limit: [150, 150]).processed
    end
  end

  def files_as_thumbnails(list)
    list.variant(resize_to_limit: [200, 200]).processed
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    if params[:query].present?
      @lists = List.where("title LIKE ?", "%#{params[:query]}%")
    else
      @lists = List.all.order('created_at DESC')
    end

    # Not too clean but it works!
    if turbo_frame_request?
      render partial: "lists", locals: { lists: @lists }
    else
      render :index
    end
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:title,
        :image, :body, files: [])
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :files, style: "display: block" %>
    <%= form.file_field :files, multiple: true %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Title:</strong>
    <%= list.title %>
  </p>
  <hr />
  <% if list.image.content_type.in?(%w[image/jpeg image/png image/jpg]) %>
    <%= link_to image_tag(list.image,
    style:"width:300px, height:300px"), list.image %>
  <% end %>
  <hr />
  <% if list.files.attached? %>
    <% list.files.each do |attachment| %>
      <% if attachment.image? %>
        <%= link_to image_tag(attachment,
          style:"width:200px, height:auto"),
          attachment %>
      <% elsif attachment.audio? %>
        <audio controls>
          <source src="<%= rails_blob_url(attachment) %>"
            type="<%= attachment.content_type %>" />
        </audio>
      <% elsif attachment.video? %>
        <video controls width="480">
          <source src="<%= rails_blob_url(attachment) %>"
            type="<%= attachment.content_type %>" />
        </video>
      <% else %>
        <%= link_to attachment.filename,
        rails_blob_path(attachment, disposition: "attachment") %>
      <% end %>
    <% end %>
  <% end %>
  <hr />
  <%= list.body %>
  <br />
</div>

app/views/lists/_lists.html.erb
<!-- app/views/bands/_bands.html.erb-->
<%= turbo_frame_tag "lists" do %>
  <%= render lists %>
<% end >

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>
<%= link_to "New list", new_list_path %>
<hr />
<%= form_with(url: lists_path, method: :get,
data: {controller: "search-form", turbo_frame: "lists", turbo_action: "advance"}) do |form| %>
  <%= form.label :query, "Search by list title:", class: "block mb-2" %>
  <div class="flex space-x-3">
    <%= form.text_field :query, class: "py-2 px-3 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none" %>

    <%= form.submit 'Search', class: "px-3 py-2 font-medium bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
  </div>
<% end %>
<hr />
<div id="lists">
  <% @lists.each do |list| %>
  <div class="row  mt-4 clearfix">
    <div class="col-8 col-sm-8 col-md-9 col-lg-9">
      <h5 class="mt-0 mb-1">
        <a href="/lists/<%= list.id %>",
        class="nav-link"><%= list.title %></a>
      </h5>
      <%= truncate(strip_tags(list.body.to_s), length:160) %>
    </div>
    <div class="col-4 col-sm-4 col-md-3 col-lg-3 clearfix">
      <% if list.image.attached? %>
        <%= link_to image_tag(list.image,
        style:"width:160px; heigh:auto"), list.image %>
      <% end %>
    </div>
  </div>
  <hr />
  <% end %>
</div>
<br />
<%= link_to "New list", new_list_path %>
<br />
<hr />

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>
</div>
<hr />
<h1><%= @list.title %></h1>
<div id="navbar" class="1collapse">
  <ul class="nav navbar-nav">
    <li class="">
      <p style="width:650px; heigh:auto">
      <% if @list.image.attached? %>
        <%= link_to image_tag(@list.image,
        style:"width:640px; heigh:auto"), @list.image %>
      <% end %>
      </p>
    </li>
    <li>
      <p style="width:400px; heigh:auto">
        <%= @list.body %>
      </p>
    </li>
    <li class="">
      <% if @list.files.attached? %>
        <% @list.files.each do |attachment| %>
          <% if attachment.image? %>
            <%= image_tag attachment, width: "200px" %>
          <% elsif attachment.audio? %>
            <audio controls>
              <source src="<%= rails_blob_url(attachment) %>"
                type="<%= attachment.content_type %>" />
            </audio>
          <% elsif attachment.video? %>
            <video controls width="720">
              <source src="<%= rails_blob_url(attachment) %>"
                type="<%= attachment.content_type %>" />
            </video>
          <% else %>
            <%= link_to attachment.filename,
            rails_blob_path(attachment, disposition: "attachment") %>
          <% end %>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>
<hr />
<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @alist, method: :delete %>
</div>
<hr />
<br />