config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/art'
  resources :articles
  resources :posts
  devise_for :users
  resources :movies
  get 'home/index'
  resources :lists
  #root "articles#index"
  root "home#index"
  #root "pages#art"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many_attached :pictures
  has_rich_text :body

  def image_as_thumbnail
    return unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    image.variant(resize_to_limit: [300, 300]).processed
  end

  def pictures_as_thumbnails
    pictures.map do |picture|
      picture.variant(resize_to_limit: [150, 150]).processed
    end
  end

  def pictures_as_thumbnails(article)
    article.variant(resize_to_limit: [200, 200]).processed
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    if params[:query].present?
      @articles = Article.where("title LIKE ?", "%#{params[:query]}%")
    else
      @articles = Article.all.order('created_at DESC')
    end

    # Not too clean but it works!
    if turbo_frame_request?
      render partial: "articles", locals: { articles: @articles }
    else
      render :index
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title,
        :body, :publish, :image, pictures: [])
        .with_defaults(user: current_user)
    end

    def current_user
      User.first
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="text-lg leading-loose">
    <%= link_to article.title, article_path(article), class: "text-orange-600 underline hover:text-orange-700" %>
  </p>
  <% if article.image.content_type.in?(%w[image/jpeg image/png image/jpg]) %>
    <%= link_to image_tag(article.image,
    style:"width:300px, height:300px"), article.image %>
  <% end %>
  <hr />
  <p>
    <strong>Publish:</strong>
    <%= article.publish %>
  </p>
  <%= article.body %>
  <br />
  <% if article.pictures.attached? %>
    <% article.pictures.each do |attachment| %>
       <% if attachment.image? %>
         <%= image_tag attachment, width: "200px" %>
       <% elsif attachment.audio? %>
         <audio controls>
           <source src="<%= rails_blob_url(attachment) %>"
             type="<%= attachment.content_type %>" />
         </audio>
       <% elsif attachment.video? %>
         <video controls width="480">
           <source src="<%= rails_blob_url(attachment) %>"
             type="<%= attachment.content_type %>" />
         </video>
       <% else %>
         <%= link_to attachment.filename,
         rails_blob_path(attachment, disposition: "attachment") %>
       <% end %>
    <% end %>
  <% end %>
</div>

app/views/articles/_articles.html.erb
<!-- app/views/bands/_bands.html.erb-->
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end >

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :publish, style: "display: block" %>
    <%= form.date_field :publish %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.label :pictures, style: "display: block" %>
    <%= form.file_field :pictures, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>
<%= link_to "New article", new_article_path %>
<hr />
<%= form_with(url: articles_path, method: :get,
data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
  <%= form.label :query, "Search by article title:", class: "block mb-2" %>
  <div class="flex space-x-3">
    <%= form.text_field :query, class: "py-2 px-4 rounded border ring-0 focus:ring-4
    focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none"%>

    <%= form.submit 'Search', class: "px-3 py-2 font-medium bg-orange-300 text-neutal-900
    rounded flex items-center cursor-pointer hover:bg-orange-400 1focus:ring-4 ring-0 1focus:ring-orange-100"%>
  </div>
<% end %>
<hr />
<div id="articles">
  <% @articles.each do |article| %>
  <div class="row  mt-4 clearfix">
    <div class="col-8 col-sm-8 col-md-9 col-lg-9">
      <h5 class="mt-0 mb-1">
        <a href="/articles/<%= article.id %>",
        class="nav-link"><%= article.title %></a>
      </h5>
      <time class="dateline text-muted" role="" itemprop="datePublished" datetime="28.03.2023 09:13" data-timestamp="1679987580">
        <small><%= article.publish %></small>
      </time>
      <%= truncate(strip_tags(article.body.to_s), length:180) %>
    </div>
    <div class="col-4 col-sm-4 col-md-3 col-lg-3 clearfix">
      <% if article.image.attached? %>
        <%= link_to image_tag(article.image,
        style:"width:200px; heigh:auto"), article.image %>
      <% end %>
    </div>
  </div>
  <hr />
  <% end %>
</div>
<%= link_to "New article", new_article_path %>
<br />
<hr />

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>
</div>
<hr />
<h1><%= @article.title %></h1>
<h5><%= @article.publish %></h5>
<div id="navbar" class="1collapse">
  <ul class="nav navbar-nav">
    <li class="">
      <p style="width:650px; heigh:auto">
      <% if @article.image.attached? %>
        <%= link_to image_tag(@article.image,
        style:"width:640px; heigh:auto"), @article.image %>
      <% end %>
      </p>
    </li>
    <li>
      <p style="width:400px; heigh:auto">
        <%= @article.body %>
      </p>
    </li>
    <li class="">
      <% if @article.pictures.attached? %>
        <% @article.pictures.each do |attachment| %>
          <% if attachment.image? %>
            <%= image_tag attachment, width: "200px" %>
          <% elsif attachment.audio? %>
            <audio controls>
              <source src="<%= rails_blob_url(attachment) %>"
                type="<%= attachment.content_type %>" />
            </audio>
          <% elsif attachment.video? %>
            <video controls width="720">
              <source src="<%= rails_blob_url(attachment) %>"
                type="<%= attachment.content_type %>" />
            </video>
          <% else %>
            <%= link_to attachment.filename,
            rails_blob_path(attachment, disposition: "attachment") %>
          <% end %>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>
<hr />
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>
<hr />
<br />