config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/art'
  resources :articles
  resources :posts
  devise_for :users
  resources :movies
  get 'home/index'
  resources :lists
  #root "articles#index"
  root "home#index"
  #root "pages#art"
end

app/views/layouts/_alert.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer__inner">
      <div class="footer__item">
        <form action="//getbootstrap.us13.list-manage.com/subscribe/post?u=e3428dd6b8fda73bc5ba8b6e6&amp;id=198881a019" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate="">
          <div class="d-md-flex justify-content-between align-items-center">
            <div class="form-group">
              <h5 class="mb-1">Get new themes in your inbox!</h5>
              <div class="form-text mt-0">New themes or big discounts. Never spam.</div>
            </div>
            <div id="signup_footer" class="d-flex align-items-start">
              <div class="form-group w-100 mr-2">
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e3428dd6b8fda73bc5ba8b6e6_198881a019" tabindex="-1" value=""></div>
                  <input id="mce-EMAIL" class="footer__email-input form-control form-control--muted" name="EMAIL"
                  type="email" aria-describedby="footerEmail" placeholder="Email address">
                </div>
                <input class="btn btn-brand" type="submit" value="Subscribe" name="subscibe" id="mc-embedded-subscribe">
            </div>
          </div>
        </form>
      </div>
      <div class="footer__item d-lg-flex justify-content-lg-between align-items-lg-center">
        <ul id="menu-seller-footer" class="nav sub-nav footer__sub-nav"><li id="menu-item-1333" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1333"><a title="Help Center" href="https://themes.zendesk.com/hc/en-us">Help Center</a></li>
          <li id="menu-item-1335" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1335"><a title="Terms of Service" href="https://themes.getbootstrap.com/terms/">Terms of Service</a></li>
          <li id="menu-item-1334" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1334"><a title="Licenses" href="https://themes.getbootstrap.com/licenses/">Licenses</a></li>
          <li id="menu-item-49443" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-49443"><a title="Sell Themes" href="https://themes.getbootstrap.com/sell/">Sell Themes</a></li>
        </ul>                        <p class="hidden-sm-down d-none d-lg-block">Trying to redownload a theme? Use our <a href="https://themes.getbootstrap.com/redownload/">redownload page.</a></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_img.html.erb
<img sizes="(max-width: 30em) 100vw,
            (max-width: 50em) 50vw,
            calc(33vw - 100px)"
    srcset="swing-200.jpg 200w,
            swing-400.jpg 400w,
            swing-800.jpg 800w,
            swing-1600.jpg 1600w"
    src="swing-400.jpg" alt="Kettlebell Swing">

    src="svg.jpeg"

app/views/layouts/_n.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
          <div class="container"><a href="https://themes.getbootstrap.com" class="navbar-brand">Bootstrap Themes</a>
            <div class="d-flex ml-auto">
                            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#globalNavbar" aria-controls="globalNavbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            </div>
            <div class="navbar-collapse collapse" id="globalNavbar" style="">
              <form class="form-inline form-navbar my-2 my-lg-0 order-2" action="https://themes.getbootstrap.com/shop/">
                <input class="form-control" name="s" type="text" placeholder="Search">
              </form>
              <ul class="navbar-nav mr-auto order-1">
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <div class="navbar-collapse navbar-top-collapse"><ul id="menu-top-menu" class="nav navbar-nav"><li id="menu-item-601" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-601"><a title="Admin &amp; Dashboard" href="https://themes.getbootstrap.com/product-category/admin-dashboard/">Admin &amp; Dashboard</a></li>
<li id="menu-item-603" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-603"><a title="Landing &amp; Corporate" href="https://themes.getbootstrap.com/product-category/landing-corporate/">Landing &amp; Corporate</a></li>
<li id="menu-item-1537" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1537"><a title="Application" href="https://themes.getbootstrap.com/product-category/application/">Application</a></li>
<li id="menu-item-602" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-602"><a title="E-Commerce &amp; Retail" href="https://themes.getbootstrap.com/product-category/ecommerce-retail/">E-Commerce &amp; Retail</a></li>
<li id="menu-item-1538" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1538"><a title="Portfolio &amp; Blog" href="https://themes.getbootstrap.com/product-category/portfolio-blog/">Portfolio &amp; Blog</a></li>
<li id="menu-item-1539" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent menu-item-1539"><a title="Specialty" href="https://themes.getbootstrap.com/product-category/specialty/">Specialty</a></li>
</ul></div>
                  </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/official-themes">Why Our Themes?</a></li>
                <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/guide">The Guide</a></li>
                              </ul>
                              <ul class="navbar-nav d-none d-lg-flex ml-2 order-3">
                                    <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/signin/">Sign in</a></li>
                  <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/my-account/">Sign up</a></li>
                </ul>
                <ul class="navbar-nav d-lg-none">
                  <li class="nav-item-divider"></li>
                  <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/signin/">Sign in</a></li>
                  <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/my-account/">Sign up</a></li>
                </ul>
                          </div>
          </div>
        </nav>

app/views/layouts/_na.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a href="https://themes.getbootstrap.com"
    class="navbar-brand">Bootstrap Themes</a>
    <div class="d-flex ml-auto">
      <button class="navbar-toggler collapsed"
      type="button" data-toggle="collapse"
      data-target="#globalNavbar" aria-controls="globalNavbar"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="globalNavbar" style="">
      <form class="form-inline form-navbar my-2 my-lg-0 order-2"
      action="https://localhost:3000/articles/">
        <input class="form-control" name="s" type="text" placeholder="Search">
      </form>
      <%= form_with(url: articles_path, method: :get,
      data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
        <%= form.label :query, "Search by article title:", class: "block mb-2" %>
        <%= form.text_field :query %>
        <%= form.submit 'Search' %>
      <% end %>
      <ul class="navbar-nav mr-auto order-1">
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <div class="navbar-collapse navbar-top-collapse">
              <ul id="menu-top-menu" class="nav navbar-nav">
                <li id="menu-item-601" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-601">
                  <a title="Admin &amp; Dashboard" href="https://themes.getbootstrap.com/product-category/admin-dashboard/">Admin &amp; Dashboard</a></li>
                <li id="menu-item-603" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent menu-item-603">
                  <a title="Landing &amp; Corporate" href="https://themes.getbootstrap.com/product-category/landing-corporate/">Landing &amp; Corporate</a></li>
                <li id="menu-item-1537" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1537">
                  <a title="Application" href="https://themes.getbootstrap.com/product-category/application/">Application</a></li>
                <li id="menu-item-602" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-602">
                  <a title="E-Commerce &amp; Retail" href="https://themes.getbootstrap.com/product-category/ecommerce-retail/">E-Commerce &amp; Retail</a></li>
                <li id="menu-item-1538" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1538">
                  <a title="Portfolio &amp; Blog" href="https://themes.getbootstrap.com/product-category/portfolio-blog/">Portfolio &amp; Blog</a></li>
                <li id="menu-item-1539" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1539">
                  <a title="Specialty" href="https://themes.getbootstrap.com/product-category/specialty/">Specialty</a></li>
              </ul>
            </div>
          </div>
        </li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/official-themes">Why Our Themes?</a></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/guide">The Guide</a></li>
      </ul>
      <ul class="navbar-nav d-none d-lg-flex ml-2 order-3">
        <li class="nav-item">
          <a class="nav-link"
          href="/users/sign_in/">
          Sign in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
          href="/users/sign_up/">
          Sign up</a>
        </li>
      </ul>
      <ul class="navbar-nav d-lg-none">
        <li class="nav-item-divider"></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/signin/">Sign in</a></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/my-account/">Sign up</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_nav1.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a href="https://themes.getbootstrap.com"
    class="navbar-brand">Bootstrap Themes</a>
    <div class="d-flex ml-auto">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#globalNavbar" aria-controls="globalNavbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    </div>
    <div class="collapse navbar-collapse" id="globalNavbar">
      <form class="form-inline form-navbar my-2 my-lg-0 order-2" action="https://themes.getbootstrap.com/shop/">
        <input class="form-control" name="s" type="text" placeholder="Search">
      </form>
      <ul class="navbar-nav mr-auto order-1">
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink"
          href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <div class="navbar-collapse navbar-top-collapse">
              <ul id="menu-top-menu" class="nav navbar-nav"><li id="menu-item-601" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-601"><a title="Admin &amp; Dashboard" href="https://themes.getbootstrap.com/product-category/admin-dashboard/">Admin &amp; Dashboard</a></li>
                <li id="menu-item-603" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent menu-item-603"><a title="Landing &amp; Corporate" href="https://themes.getbootstrap.com/product-category/landing-corporate/">Landing &amp; Corporate</a></li>
                <li id="menu-item-1537" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1537"><a title="Application" href="https://themes.getbootstrap.com/product-category/application/">Application</a></li>
                <li id="menu-item-602" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-602"><a title="E-Commerce &amp; Retail" href="https://themes.getbootstrap.com/product-category/ecommerce-retail/">E-Commerce &amp; Retail</a></li>
                <li id="menu-item-1538" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1538"><a title="Portfolio &amp; Blog" href="https://themes.getbootstrap.com/product-category/portfolio-blog/">Portfolio &amp; Blog</a></li>
                <li id="menu-item-1539" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1539"><a title="Specialty" href="https://themes.getbootstrap.com/product-category/specialty/">Specialty</a></li>
              </ul>
            </div>
          </div>
        </li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/official-themes">Why Our Themes?</a></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/guide">The Guide</a></li>
      </ul>
      <ul class="navbar-nav d-none d-lg-flex ml-2 order-3">
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/signin/">Sign in</a></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/my-account/">Sign up</a></li>
      </ul>
      <ul class="navbar-nav d-lg-none">
        <li class="nav-item-divider"></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/signin/">Sign in</a></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/my-account/">Sign up</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_nav2.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a href="https://themes.getbootstrap.com"
    class="navbar-brand">Bootstrap Themes</a>
    <div class="d-flex ml-auto">
      <button class="navbar-toggler" type="button"
      data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Lists', lists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: "nav-link" %>
        </li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/official-themes">Why Our Themes?</a></li>
        <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/guide">The Guide</a></li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Posts', posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Setting
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_user.email}",
               edit_user_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= button_to(
                "Log Out",
                destroy_user_session_path,
                method: :delete
              ) %>
            <% else %>
            <li>
              <%= link_to "Sign In",
               new_user_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_user_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <li><a class="dropdown-item"  title="Admin &amp; Dashboard" href="https://themes.getbootstrap.com/product-category/admin-dashboard/">Admin &amp; Dashboard</a></li>
            <li><a class="dropdown-item"  title="Landing &amp; Corporate" href="https://themes.getbootstrap.com/product-category/landing-corporate/">Landing &amp; Corporate</a></li>
            <li><a class="dropdown-item"  title="Application" href="https://themes.getbootstrap.com/product-category/application/">Application</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item"  title="E-Commerce &amp; Retail" href="https://themes.getbootstrap.com/product-category/ecommerce-retail/">E-Commerce &amp; Retail</a></li>
            <li><a class="dropdown-item"  title="Portfolio &amp; Blog" href="https://themes.getbootstrap.com/product-category/portfolio-blog/">Portfolio &amp; Blog</a></li>
            <li><a class="dropdown-item"  title="Specialty" href="https://themes.getbootstrap.com/product-category/specialty/">Specialty</a></li>
          </ul>
        </li>
        <%= form_with(url: articles_path, method: :get,
        data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
          <%= form.text_field :query, class: "py-2 px-4 rounded border ring-0 focus:ring-4
            focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none"%>

          <%= form.submit 'Search', class: "px-3 py-2 font-medium bg-orange-300 text-neutal-900
            rounded flex items-center cursor-pointer hover:bg-orange-400 1focus:ring-4 ring-0 1focus:ring-orange-100"%>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navb.html.erb
<iframe src="https://www.tumblr.com/dashboard/iframe?tumblelogName=halcyon-theme&amp;src=https%3A%2F%2Fhalcyon-theme.tumblr.com%2F#%7B%22searchQuery%22%3A%22%22%2C%22pushDown%22%3Atrue%2C%22useThemeColors%22%3Atrue%2C%22scrollHeader%22%3Afalse%2C%22themeHeaderImage%22%3A%22https%3A%2F%2Fassets.tumblr.com%2Fimages%2Fdefault_header%2Foptica_pattern_08_focused_v3.png%3F_v%3Df0f055039bb6136b9661cf2227b535c2%22%2C%22themeBackgroundColor%22%3A%22%23FFFFFF%22%2C%22themeTitleColor%22%3A%22%23000000%22%2C%22themeAccentColor%22%3A%22%2300B8FF%22%2C%22isOpticaLike%22%3Afalse%2C%22shouldHideBlogSearchBar%22%3Afalse%7D" width="281" height="54" frameborder="0" scrolling="no" name="unified-controls"
class="tmblr-iframe tmblr-iframe--unified-controls tmblr-iframe--loaded iframe-controls--desktop">
</iframe>
<div class="ui_dialog_lock" style="display: none;"></div>

app/views/layouts/a.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Setting
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <div class="navbar-collapse navbar-top-collapse">
      <ul id="menu-top-menu" class="nav navbar-nav">
        <li id="menu-item-601" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-601">
          <a title="Admin &amp; Dashboard" href="https://themes.getbootstrap.com/product-category/admin-dashboard/">Admin &amp; Dashboard</a></li>
        <li id="menu-item-603" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent menu-item-603">
          <a title="Landing &amp; Corporate" href="https://themes.getbootstrap.com/product-category/landing-corporate/">Landing &amp; Corporate</a></li>
        <li id="menu-item-1537" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1537">
          <a title="Application" href="https://themes.getbootstrap.com/product-category/application/">Application</a></li>
        <li id="menu-item-602" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-602">
          <a title="E-Commerce &amp; Retail" href="https://themes.getbootstrap.com/product-category/ecommerce-retail/">E-Commerce &amp; Retail</a></li>
        <li id="menu-item-1538" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1538">
          <a title="Portfolio &amp; Blog" href="https://themes.getbootstrap.com/product-category/portfolio-blog/">Portfolio &amp; Blog</a></li>
        <li id="menu-item-1539" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1539">
          <a title="Specialty" href="https://themes.getbootstrap.com/product-category/specialty/">Specialty</a></li>
      </ul>
    </div>
  </div>
</li>

<li><a class="dropdown-item" href="#">Action</a></li>
<li><a class="dropdown-item" href="#">Another action</a></li>
<li><a class="dropdown-item" href="#">Something else here</a></li>

<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink"
  href="#" data-toggle="dropdown" aria-haspopup="true"
  aria-expanded="false">Categories</a>
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Setting
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <div class="navbar-collapse navbar-top-collapse">
      <ul id="menu-top-menu" class="nav navbar-nav">
        <li id="menu-item-601" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-601">
          <a title="Admin &amp; Dashboard" href="https://themes.getbootstrap.com/product-category/admin-dashboard/">Admin &amp; Dashboard</a></li>
        <li id="menu-item-603" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent menu-item-603">
          <a title="Landing &amp; Corporate" href="https://themes.getbootstrap.com/product-category/landing-corporate/">Landing &amp; Corporate</a></li>
        <li id="menu-item-1537" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1537">
          <a title="Application" href="https://themes.getbootstrap.com/product-category/application/">Application</a></li>
        <li id="menu-item-602" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-602">
          <a title="E-Commerce &amp; Retail" href="https://themes.getbootstrap.com/product-category/ecommerce-retail/">E-Commerce &amp; Retail</a></li>
        <li id="menu-item-1538" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1538">
          <a title="Portfolio &amp; Blog" href="https://themes.getbootstrap.com/product-category/portfolio-blog/">Portfolio &amp; Blog</a></li>
        <li id="menu-item-1539" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-1539">
          <a title="Specialty" href="https://themes.getbootstrap.com/product-category/specialty/">Specialty</a></li>
      </ul>
    </div>
  </div>
</li>
<ul class="navbar-nav d-lg-none">
  <li class="nav-item-divider"></li>
  <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/signin/">Sign in</a></li>
  <li class="nav-item"><a class="nav-link" href="https://themes.getbootstrap.com/my-account/">Sign up</a></li>
</ul>
<ul class="navbar-nav d-none d-lg-flex ml-2 order-3">
  <li class="nav-item">
    <a class="nav-link"
    href="/users/sign_in/">
    Sign in</a>
  </li>
  <li class="nav-item">
    <a class="nav-link"
    href="/users/sign_up/">
    Sign up</a>
  </li>
</ul>
<a class="navbar-brand" href="#">Ruby on Rails</a>
<%= form.label :query, "Search by article title:", class: "block mb-2" %>
<html class=" js no-flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths">
action="https://themes.getbootstrap.com/shop/">
href="https://themes.getbootstrap.com/signin/">
href="https://themes.getbootstrap.com/my-account/">
<div class="flex space-x-3">
</div>
, class: "py-3 px-4 rounded border ring-0
focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none"
, class: "px-4 py-3 font-medium bg-orange-300 text-neutal-900
rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100"
, class:"form-inline form-navbar my-2 my-lg-0 order-2"

app/views/layouts/application4.html.erb
<!DOCTYPE html>
<html class=" js no-flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths">
  <head>
    <title>My Bootstrap Example</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="product-template-default single single-product postid-21888 woocommerce theme-dokan woocommerce-page woocommerce-js dokan-theme-dokan">
    <section class="section-1">
      <p>This is the current section</p>
      <img src="swing-400.jpg">
    </section>
    <section class="section-2 hidden">
      <p>This is the current section</p>
      <img src="example-2.png">
    </section>
  </body>
</html>

app/views/layouts/form.html.erb
<form class="d-flex" role="search">
  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>